version: 2
updates:
  - package-ecosystem: docker
    directory: "/8.1-cli"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/8.2-cli"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
